### ISSUE TITLE
Wrong declaration!

### ISSUE THREAD

**Issue by jaytarka** [eapache/starscope#123]
Very sorry to report this, but it just doesn't seem to be working properly:

This is the incorrect reference, as directed by starscope:
![image](https://cloud.githubusercontent.com/assets/13591429/9735583/bfbe7eb0-5633-11e5-8503-1a04c50ff440.png)

That reference is actually to a private method, so it is certainly incorrect.

This is the correct reference, as directed by rubymine:
![image](https://cloud.githubusercontent.com/assets/13591429/9735586/c7a1fabc-5633-11e5-806c-91900f48dbc7.png)

**Comment by eapache** [comment]
Thanks for the report, I'm going to need a bit more information in order to track this down.
- What version of starscope are you using?
- Is this incorrect reference via a starscope query, or via ctags/cscope export?
- Is the source code in question publicly available? If so, where is it? If not, can you send me a minimal sample to reproduce with?

Thanks,
Evan

**Comment by eapache** [comment]
Based on https://stackoverflow.com/questions/32458486/is-there-a-ruby-specific-alternative-to-ctags I'm going to assume you were searching via ctags, in which case Sergio's comment is correct: "short of actually running your code, there's no bulletproof way of dereferencing names".

However, there is at least a partial workaround. If you generate a cscope database as well (using starscope) and configure vim correctly (I believe you want `set cscopetag` and `set csto=1` in your `.vimrc` but I'm not 100% sure) then when it finds an ambiguous symbol it will ask you which one you want to jump to. This isn't quite as awesome as it just going to the right one automatically, but it's a lot better than just going to the wrong one :)

**Comment by jaytarka** [comment]
eapache sorry for not getting back earlier. thankyou!
