### ISSUE TITLE
line_for_record returning nil when exporting in ruby project

### ISSUE THREAD

**Issue by iamcz** [eapache/starscope#148]
I'm trying to use starscope with the ruby project (https://github.com/ruby/ruby) and exporting fails for ctags and cscope. I traced the error back to line_for_record, which seems to be returning `nil`.

I'm not sure of the root cause of this problem. Perhaps it is because the source code is a mix between Ruby and C. This might not be an issue if starscope is not meant to be used for mixed source projects, although I've tried it on a gem with a C extension and exporting didn't fail.

**Comment by eapache** [comment]
Mixed language *shouldn't* be a problem unless some files are getting mis-detected. Which version of starscope are you using?

**Comment by iamcz** [comment]
Version 1.5.1

**Comment by eapache** [comment]
OK, gave this a quick look. I assume you're parsing the trunk of `ruby/ruby`, in which case you probably saw the following error scroll past while building the initial starscope db:
```
Starscope::Lang::Ruby raised "undefined method `name' for #<Parser::Source::Map:0x000000017cc288>" while extracting test/csv/test_encodings.rb
```
Ruby's trunk has made some syntax changes which are causing the parser (https://github.com/whitequark/parser) to fail. Starscope tries to be resilient and just skip the file when that happens, but I guess some bad data is still ending up in the database.

Your best bet is to manually upgrade to the pre-release parser gem (v2.3.0.pre.4) which *should* support the syntax in ruby's trunk. As far as I can tell once the parser is working Starscope should be able to export again. I'll also look at improving the resiliency here (and maybe better error messages).

**Comment by iamcz** [comment]
I tried installing parser v2.3.0.pre.4 and it looks like there's a dependency error which is forcing me back to starscope version 1.3.1. Tried rebuilding the database but all starscope commands fail with a LoadError coming from backports (from parser). `cannot load such file -- parser/ruby22 (LoadError)`.

**Comment by eapache** [comment]
With the relaxed version requirement, does installing the parser pre-release solve this issue?
