### ISSUE TITLE
cannot install starscope on jRuby 9.1.6

### ISSUE THREAD

**Issue by programmertoni** [eapache/starscope#162]
when running
```
$ gem install starscope
```

I get this error
```
Fetching: oj-2.18.0.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing starscope:
        ERROR: Failed to build gem native extension.
```

EDIT:

I also tried to enable C extensions for jRuby and got the same error
```
$ JRUBY_OPTS="-Xcext.enabled=true" gem install starscope
```

**Comment by eapache** [comment]
Starscope depends on OJ (https://github.com/ohler55/oj) for json parsing; I just saw this in the OJ readme:

> Support for JRuby has been removed as JRuby no longer supports C extensions and there are bugs in the older versions that are not being fixed.

I suppose it might be possible to switch back to the built-in json gem but it is substantially slower.

**Comment by programmertoni** [comment]
Thank you for quick reply.
 
My workaround with this issue is just to switch to cRuby and generate cTags using starscope. I will probably write shell script to do this switching.

I also like to thank you for creating this wonderful tool. I was playing with starscope yesterday and I am impressed.

**Comment by eapache** [comment]
Thank you :)
