### ISSUE TITLE
Consider adding sym table export to ctags

### ISSUE THREAD

**Issue by jackkinsella** [eapache/starscope#170]
I'm using starscope to generate ctags which in turn powers my auto-complete in vim. This works majestically for function definitions and constants, but it doesn't pick up symbols.

For example, in Rails I might write:

```ruby
   has_many :orders, dependent: :restrict_with_exception
```

With the current workflow, the `:restrict_with_exception` symbol will not be available in other buffers.

What are your thoughts on adding syms to the ctag format exports? Or at least allowing an option for this. Happy to make a PR if this is something you'd consider.

**Comment by jackkinsella** [comment]
You're right. It sort of breaks the semantics. Perhaps there could be an option to export a general sym list into a plaintext file that could be read as a source for autocomplete plugins.

**Comment by eapache** [comment]
Ya, something like that would probably work. You might also be able to get what you want via the cscope export?
