### ISSUE TITLE
Cscope generation conflicts between class defs and reads

### ISSUE THREAD

**Issue by jmmgr** [eapache/starscope#176]
Hi, 

I have `starscope 1.5.6`  (tried with `1.5.7` and same result) I'm generated files from a Ruby code base.

When I run 
`starscope -e cscope`

It will generate `cscope.out` with:
```
4 class 
ExampleClass
 < 
ExampleClass2
```

The problem is this format doesn't seems to be able to get the definitions of cscope:
```
cscope -f ~/git/cscope.out -dL1 ExampleClass # empty result bad
cscope -f ~/git/cscope.out -dL0 ExampleClass  # result is ok
```

If I do the same operations with a `cscope.out` I generated in the past it works. The difference I see is the `cscope.out` would define the class as:
```
4 class 
	cExampleClass
 < 
ExampleClass2
```

When I check directly with the Starscope DB it works:
```
starscope -q lang:ruby,defs,ExampleClass
```

So the problem may be related with the generation of `scope.out`

Thanks!

**Comment by eapache** [comment]
It would help me a lot to debug if you could share a snippet of the code that is being scanned or the starscope database that's being used to generate the export.  Right now I don't have enough information to figure out where the bug might be.

**Comment by jmmgr** [comment]
Hi!
No problem.
I have the file `test.rb`
```
class ExampleClass
  def self.hello
    puts 'hello'
  end
end

ExampleClass.hello
```
I generate the `cscope.out`:

```
starscope -e cscope
```

Result:
starscope query works correctly:
```
starscope -q lang:ruby,defs,ExampleClass
# No changes detected.
# ExampleClass -- test.rb:1 (class ExampleClass
```
Cscope find by symbol works correctly:
```
cscope -dL0 ExampleClass
# test.rb - 1 class ExampleClass
# test.rb - 7  ExampleClass.hello
```
Cscope find by definition the class doesn't work
```
cscope -dL1 ExampleClass
# ( empty result)
```

Cscope find by definition the method works
```
cscope -dL1 hello
# test.rb hello 2  def self.hello
```

In my previous use of Starscope I was able to find the Class definitions.

Thanks!

**Comment by jmmgr** [comment]
Hi, 
I've been trying to debug the problem, what I found out:

- The .starscope.db generates 2 lines about the class `ExampleClass`
```
	":defs":[
		{ ":line_no":1, ":type":":class", ":col":6, ":file":"test.rb", ":name":[":ExampleClass"] },
.....

	":reads":[
		{ ":line_no":1, ":col":6, ":file":"test.rb", ":name":[":ExampleClass"] },
.....
```
So we have one `def` and one `reads` both with the same `line_no`, `col`, and `name`.

Then in the `exportable.rb`, when we are trying to convert it to `cscope`, we will write only one of them [here](https://github.com/eapache/starscope/blob/master/lib/starscope/exportable.rb#L195) 
The `reads` will replace the `defs`, because they have the same `key` and `col`.

If I remove this [line](https://github.com/eapache/starscope/blob/master/lib/starscope/langs/ruby.rb#L102) and I don't generate the `reads`, the cscope will be generated correctly. But not sure which side effects may have.

Thanks!

**Comment by eapache** [comment]
Sorry it took me a while to get back to this, and thanks for digging! Removing the line you proposed would unfortunately break cscope's find-by-symbol for most ruby constant usages.

I see two options, neither of which are ideal.
- Put a condition around the `yield :reads` you identified so that it doesn't run if the constant being "read" is actually part of a definition. This is probably more correct, but I'm not sure how to do it reliably given the complications of the ruby AST.
- Fix `tokenize_line` in `exportable.rb` to pick the "best" record for a given index instead of simply the last record for a given index. This might even be as simple as replacing the final `toks[index] =` with a `||=` or we might want to do a more complete check.

**Comment by eapache** [comment]
I just pushed a commit to the main branch which *should* fix this issue, though again it's a tricky one. Please let me know if it doesn't work, or if you have any more problems!
