### ISSUE TITLE
add sample .starscope.json for reference

### ISSUE THREAD

**Issue by twnaing** [eapache/starscope#179]
Can you please add a sample (annotated if possible) `.starscope.json` for reference?

Currently, there is only one mention of `.starscope.json` about excluding files and I want to know the followings

- is it possible to source `.ctags` file it is present in the directory? (the reason is ctags supports ruby and there are quite some tools available for ctags e.g. gem-ctags, but cscope support for ruby is poor)
- what are the patterns we can use to exclude files and folders?
- command line `--exclude` is the same as json file `"excludes"`?
- how can I view the currently excluded file/folders?
- do I need to run `starscope` before I export the cscope format? 

I assume I need to and if I am correct, the document should explicitly say so.

**Comment by eapache** [comment]
Good question, I'll try and write up something better at some point. In the meantime:

> is it possible to source .ctags file it is present in the directory? (the reason is ctags supports ruby and there are quite some tools available for ctags e.g. gem-ctags, but cscope support for ruby is poor)

Are you asking if starscope can extract information from existing tag files? It cannot, but it can generate all the same information itself. Or have I misunderstood?

> what are the patterns we can use to exclude files and folders?

Anything supported by Ruby's `File.fnmatch?` method:
https://ruby-doc.org/core-2.5.0/File.html#method-c-fnmatch

> command line --exclude is the same as json file "excludes"?

Yes.

> how can I view the currently excluded file/folders?

`starscope --no-update --dump _excludes` will show the current list of patterns excluded from the local db. This list gets combined with the patterns in `.starscope.json`.

If you're looking for the *actual* files/folders, I don't think there's a way to get that list? It's calculated from the exclude patterns and isn't stored or output anywhere.

> do I need to run starscope before I export the cscope format?

Yes? Again I'm not sure what you're asking. You can't export to cscope without running the program, since the program is what does the export...

**Comment by twnaing** [comment]
> Are you asking if starscope can extract information from existing tag files? It cannot, but it can generate all the same information itself. Or have I misunderstood?

ctags read command-line options from `.ctags` file (like starscope use .starscope.json) `man ctags`'s FILES section tells more. Previously I used ctags and migrated to starscop. I had to migrate my .ctags to .starscope.json. If starscope could understand the .ctags file, the transition would be seamless.

> Yes? Again I'm not sure what you're asking. You can't export to cscope without running the program, since the program is what does the export...

I just wanted to confirm that because (this part of) USER GUIDE does not mention the need to run starscope before export. And I thought export command run the starscope (db generation code) before exporting.

> Just place the line starscope --quiet -e cscope & into the hooks documented by Tim.

**Comment by eapache** [comment]
> ctags read command-line options from .ctags file (like starscope use .starscope.json) man ctags's FILES section tells more. Previously I used ctags and migrated to starscop. I had to migrate my .ctags to .starscope.json. If starscope could understand the .ctags file, the transition would be seamless.

Ah, I understand now. I don't have time to add that feature myself right now, but I'd be happy to take a pull request.

> I just wanted to confirm that because (this part of) USER GUIDE does not mention the need to run starscope before export. And I thought export command run the starscope (db generation code) before exporting.

Yes, if you just run e.g. `starscope -e cscope` that will generate the database *and* do the export - you don't need to generate the database separately first.

**Comment by twnaing** [comment]
> I don't have time to add that feature myself right now, but I'd be happy to take a pull request.

What will be your preferred workflow? I am considering, "if .ctags file found, read it and merge with .starscope.json and .starscope take precedence."

**Comment by eapache** [comment]
That would make sense to me.

**Comment by eapache** [comment]
The documentation on what currently exists has been improved. I have no plans to work on importing `.ctags` files (or adding more features to `.starscope.json`) so I'm going to close this, but I'm still happy to take pull requests for those features.
