### ISSUE TITLE
Ruby 3.1.1 and version 1.6.0 Non Compliance

### ISSUE THREAD

**Issue by daBee** [eapache/starscope#191]
Installed it and nothing seems to be working.

```
>>> 12:46:26 rich@HQ3 ~ ➜ which starscope
starscope not found
>>> 12:46:47 rich@HQ3 ~ ➜ starscope -q calls,new
zsh: command not found: starscope
>>> 12:47:04 rich@HQ3 ~ ➜ gem info starscope

*** LOCAL GEMS ***

starscope (1.6.0)
    Author: Evan Huus
    Homepage: https://github.com/eapache/starscope
    License: MIT
    Installed at: /Users/rich/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0

    Smart code search and indexing
```

It's installed:

```
$ gem list
...
starscope (1.6.0)
```

**Comment by daBee** [comment]
Just by the commands in the shell, which I posted.  Outside of that, no idea why it's not reacting properly.  Here's my relevant `PATH`:

```
/Users/rich/.rbenv/shims:
/opt/homebrew/bin:
/opt/homebrew/sbin:
/usr/local/bin:
/usr/bin:
/bin:
/usr/sbin:
/sbin:
/Library/Apple/usr/bin
```

**Comment by daBee** [comment]
Not sure what I did, but it is generating something now.  The only `starscope` found is a `gem` inside `.rbenv`.  About an hour to go.  Can I point this at a `x.rb` file, specifically?

**Comment by eapache** [comment]
Glad you got it working. Yes you can point it at specific files, see  https://github.com/eapache/starscope/blob/master/doc/USER_GUIDE.md#paths for all the details.
