### ISSUE TITLE
Missing Methods in .starscope.db

### ISSUE THREAD

**Issue by daBee** [eapache/starscope#193]
I have a file with a boatload of `methods`.  It is in my system `starscope` call:

`system 'starscope --force-update zz_before.rb zz_after.rb methods.rb /users/rich/RF/RFS/'`

The method that I'm finding missing as an example, shows up in the `corpus`:

```
null,
"def get_Ontario_foods()",
null,
null,
```  

However it isn't showing up in `BBEdit`.  In fact I'm not showing any completions at all from that file.  The working file is in the same `home` directory, and isn't somehow finding the `ctags` for that location.  Not sure how to troubleshoot this.

**Comment by eapache** [comment]
I’m not entirely sure I understand your issue. What do you mean when you reference `corpus`?

Is the method showing up in the generated tag file? If it is, then that’s all that starscope can do; if BBEdit can’t find the tag file or can’t read the method, then that’s an issue with BBEdit.

If the method isn’t showing up in the generate tag file, then either starscope isn’t parsing the method properly, or something else is going on. Keep in mind that starscope will not automatically regenerate tag files; you’ll have to rerun `starscope -e ctags` to update the tag file with any newly added methods.

**Comment by daBee** [comment]
`.starscope.db` is where the `ctags` are kept, from what I understand.  The `method` shows up (first post) but I don't know how this is parsed into a `ctag`.  OK, I only had that command (first post).  The docs are unclear (no `man` page).  Is that `starscope -e ctags` to go after the generation?  The vast majority of these `methods` are much older than the beginning of adoption of `starscope`.  

I just performed it manually in `~`.  It exported to a file named `tags`.  It looks a lot better.  Exported it to the proper `path` as well.  Cheers

**Comment by eapache** [comment]
Glad you got it working!

Unfortunately I don’t think ruby gems let you install man pages. Full documentation is available at https://github.com/eapache/starscope/blob/main/doc/USER_GUIDE.md.

**Comment by daBee** [comment]
It's interesting as this was 100% command line.
