### ISSUE TITLE
Global config

### ISSUE THREAD

**Issue by eapache** [eapache/starscope#88]
It would be nice to be able to specify some sort of global configuration (`~/.starscope.config` ?) so that I don't have to keep ignoring cscope.out in all of my databases

**Comment by SShrike** [comment]
Why not obey the XDG Base Directory standard and place the configuration file under `~/.config/starscope/config`?

**Comment by eapache** [comment]
XDG is specific to Linux, while Starscope is (theoretically) cross-platform. It runs on Mac for sure, and presumably on Windows as well. Where to store configuration for cross-platform apps tends to be a [fairly contentious decision](https://discuss.atom.io/t/why-pollute-with-atom/778).

I'm not against the idea of doing it "right" for each OS I'd support, but I've never bothered pinning down what those are and it seems like an awful lot of work when popular apps like git, vim, etc. still just stick a dot-file in the user's home.
